name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Testing
        run: npm run test
        env:
          CI: true
          apiKey: ${{ secrets.REACT_APP_API_KEY }}
          authDomain: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          databaseURL: ${{ secrets.REACT_APP_DATABASE_URL }}
          projectId: ${{ secrets.REACT_APP_PROJECT_ID }}
          storageBucket: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          messagingSenderId: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          appId: ${{ secrets.REACT_APP_APP_ID }}
          measurementId: ${{ secrets.REACT_APP_MEASUREMENT_ID }}

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        env:
          CI: false
          apiKey: ${{ secrets.REACT_APP_API_KEY }}
          authDomain: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          databaseURL: ${{ secrets.REACT_APP_DATABASE_URL }}
          projectId: ${{ secrets.REACT_APP_PROJECT_ID }}
          storageBucket: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          messagingSenderId: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          appId: ${{ secrets.REACT_APP_APP_ID }}
          measurementId: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
        run: |
          git config --global user.email "${{ secrets.ACTION_EMAIL }}"
          git config --global user.name "${{ secrets.ACTION_USER_NAME }}"
          git remote set-url origin https://${{ secrets.ACTIONS_TOKEN }}@github.com/tazaryoot/pwa-wrkt.git
          npm run deploy
